coveooss/gotemplate

- Makefile
- README.md
- doc_test/arithmetic.md
- doc_test/arithmetic.razor
- doc_test/arithmetic.render
- doc_test/assignation.render
- render-doc
- template/extra_funcs.go
- template/razor.go
- tests/razor.template
- utils/reflect.go
- Add key and content to better handle hcl structures represented as …ray of maps
- Improve the merge function to handle errors
- Fix a problem with default function not rendering properly in razor mode
> Bug fixes and improvements

- main.go
- template/razor.go
- template/razor_test.go
- template/template.go
- Allow setting template options from external packages
- Fix razor expression to handle correctly single . parameter such as `@print("The content is:", .)`
- Fix razor expression to allow no parameter call such as `@function()`
> - Allow initialization of new template from a specific folder

- main.go
- template/extra_logging.go
- template/razor.go
- template/template.go
- utils/exec.go
It is now possible to define environment variable GOTEMPLATE_PATH to search for go template extension located outside the current path.
> Add GOTEMPLATE_PATH support

- TODO
- docs/Gemfile
- docs/_data/navigation.yml
- docs/assets/css/style.scss
- docs/doc_test/!Data
- docs/doc_test/!DataFile
- docs/doc_test/collections.md
- docs/doc_test/collections.razor
- docs/doc_test/collections.rendered
- docs/doc_test/data.md
- docs/doc_test/data.razor
- docs/doc_test/data.rendered
Submitting this because I'm leaving for a week
> Data and collections tests (+ documentation)

- collections/convert_data.go
- hcl/utilities.go
- xml/xml.go
Disable xml conversion since it is not yet used
Add trace on generic convertData errors
> Fix hcl conversion problem when map[string]interface{} are desired

- docs/_functions.md
- docs/_usage.md
- docs/doc_test/collections.md
- docs/doc_test/collections.razor
- docs/doc_test/collections.rendered
- docs/functions_long.md
- main.go
- template/extra_data.go
- template/razor.go
Remove the has alias for hasKey to not interfere with Sprig has function
Add shortcuts for some commands (--dl, --ll, --del)
> Fix regular expression when specifying optional delimiters

- collections/generic_list.go
- collections/implementation/generic.go
- collections/implementation/generic_test.go
- collections/implementation/list_helper.go
- docs/_functions.md
- docs/_list_methods.md
- docs/functions_long.md
- hcl/generated_impl.go
- hcl/generated_test.go
- json/generated_impl.go
- json/generated_test.go
- template/extra_data.go
- xml/generated_impl.go
- xml/generated_test.go
- yaml/generated_impl.go
- yaml/generated_test.go
- Also added Union() and Intersect() on list objects.
> Add union and intersect function

- collections/implementation/dict_helper.go
- docs/_data/navigation.yml
- docs/_functions.md
- docs/doc_test/conditionals.md
- docs/doc_test/conditionals.razor
- docs/doc_test/conditionals.rendered
- docs/doc_test/data.md
- docs/doc_test/data.razor
- docs/doc_test/data.rendered
- docs/functions_long.md
- glide.lock
- glide.yaml
- main.go
- template/extra_sprig.go
- utils/reflect_test.go
Some tests were added while trying to determine where the bug was
> Replace mergo's Merge by a homebrewed version

- main.go
* The behavior of `--base` and `--math` and other addins library was altered by a4ae53eeaf3f84a6adb2d89f9ec29ca934b4d65d
It was no longer possible to disable all plugins by specifying `--base`
* list option was crashing because the logging was only initialized in run mode.
> Fix a couple a new bugs introduced by recent changes

- .vscode/settings.json
- main.go
- render-doc
- template/add_funcs.go
- template/extra_data.go
- template/extra_math.go
- template/extra_runtime.go
- template/extra_sprig.go
- template/func_category.go
- template/func_table.go
- template/func_table_test.go
- template/template_help.go
Quick POC on autodocumenting functions, adding an example/test for each function
Exported to the doc:
This doc will be reworked btw. I plan to remove the full code box for the function and add a menu
> Allow autodocumenting functions

- collections/dictionary.go
- collections/generic_list.go
- collections/implementation/dict_helper.go
- collections/implementation/generic_test.go
- collections/implementation/list_helper.go
- context.go
- go.mod
- go.sum
- hcl/generated_test.go
- json/generated_test.go
- main.go
- template/generated_options.go
- template/math_utilities_test.go
- template/razor_test.go
- test.sh
- utils/generated_colors.go
- utils/reflect_test.go
- xml/generated_test.go
- yaml/generated_test.go
- Tests with goroutines instead of regular t.Parallel()
- Calling dictionaryHelper without a mutex from multiple tests
> Fix issues that make test -race fail

- .gitmodules
- Makefile
- collections/string_test.go
- collections/string_util.go
- docs/assets/_custom.scss
- docs_tests/basic_features/arithmetic.md
- docs_tests/basic_features/arithmetic.razor
- docs_tests/basic_features/arithmetic.rendered
- go.sum
- render-doc
- template/add_funcs.go
- template/extra_data.go
- template/extra_math.go
- template/extra_sprig.go
- template/extra_utils.go
- template/func_table.go
- template/func_table_test.go
- template/template_help.go
- Some contents forced the HTML help to scroll.
- Generate separated code block for each example
- Add some more examples
> Fix documentation rendering

- render-doc
There was an over @ before the function list
> Fix error in the rendered doc

- template/razor.go
- template/razor_repl_expr.go
- template/razor_repl_literal.go
- template/razor_test.go
I added tests to detect that specific case when using empty strings within backticks ``.
Also aded a test to validate assignation under with statement.
> There was a bug with multiline string protection

- template/extra_data_test.go
- template/extra_utils.go
- template/extra_utils_test.go
- template/razor.go
The raw function consider that en empty list of arguments is nothing instead of an empty list. Also, it considers single argument as single element instead of a list of 1 item. So, I added a function named rawList to always consider arguments as a list of items.
> Add rawList function

- .github/workflows/build.yml
- .github/workflows/pr.yml
Reverting update since the suggested hashes are not allowed.
> Revert GHA hash update CSEC-18897 CSEC-18899 CSEC-18901

- .github/workflows/codeql.yml
> Try CodeQL in Gotemplate

- collections/implementation/base_helper.go
- collections/string.go
- go.mod
- go.sum
- template/extra_data.go
- template/extra_runtime.go
- template/extra_sprig.go
- template/math_utilities_test.go
- utils/lorem_test.go
- Remove usage of deprecated functions
- Added doc for the new Sprig function sha512sum
- Fix tests in the math module that were no longer executed since ...
> Fix errors and warning after updating the libraries (2)

- main.go
- template/extra_runtime.go
- template/extra_runtime_test.go
This pull request includes several changes to the `main.go` and `template/extra_runtime.go` files to improve context handling and import organization. The most important changes include renaming a method for clarity, and optimizing template execution.
Enhancements to template context handling:
* [`template/extra_runtime.go`](diffhunk://#diff-da65b666c2f2215524381a459dbca8e5c9ebb70b0e41cb3cec3c3d3b39a545c9L170-R169): Renamed the `userContext` method to `cloneUserContext` to better reflect its functionality of cloning the user context.
* [`template/extra_runtime.go`](diffhunk://#diff-da65b666c2f2215524381a459dbca8e5c9ebb70b0e41cb3cec3c3d3b39a545c9R432-R446): Refactored the `runTemplate` method to use a new `optimizedRunTemplate` method, which includes an option to clone the context for …
> perf: Decrease execution times by 1000% [DT-7499]

- template/extra_runtime.go
We must restore the default mode to avoid error on further template evaluation
> Restore missing key default behavior
