coveooss/gotemplate

main.go
template/extra_runtime.go
template/razor.go
utils/strings.go

- Fix a problem with ellipsis function when the last argument was nil
- Fix problem where @elseif was not working properly
- Add support for $var := expression instead of @$var := expression (the simplified version, $var := ..., requires the expression to be valid go expression while the @$var := ... supports both go or go template expression.
- Add flexibility on corner cases when there is a string contains special characters such as ; @ or {}

Razor conversion improvement

---

doc_test/literals.md
doc_test/literals.razor
doc_test/literals.render
template/razor.go
template/template.go

- Fix problem with expression such as `-@var` that are interpreted as `{{- $.var }}`. They could lead to confusion. Moved the - after the @ to get the expected result `@-var` will result in `{{- $.var }}` while -@var will result in `-{{ $.var }}`
- Errors in ProcessTemplates was not handled correctly, we cannot return an errors.Array as error, it is interpreted as error event if the array is nil or empty.
- Add syntax `@{a}` to access local variables. This is equivalent to `@$a`, but less ugly.
- Add syntax `@<var` to indicate that we want a newline before the resulting value.

Change behaviour of `-@` and fix error management problem

---

collections/convert_data_test.go
collections/implementation/dict_helper_test.go
collections/implementation/generic_test.go
collections/string_test.go
context.go
hcl/generated_test.go
hcl/hcl_test.go
hcl/utilities.go
json/generated_test.go
template/extra_data_test.go
template/template_test.go
xml/generated_test.go
yaml/generated_test.go
yaml/yaml_test.go

- Run most of the tests in parallel
- Fix an Hcl rendering problem

Set default context type to the first input file type

---

collections/string.go
collections/string_test.go
docs/_functions.md
docs/doc_test/assignation.razor
docs/doc_test/collections.razor
docs/doc_test/comments.razor
docs/doc_test/literals.razor
docs/doc_test/templates.razor
docs/functions_long.md
main.go
template/extra_logging.go
template/extra_runtime.go
template/razor.go
template/template.go
utils/color.go
utils/color_test.go

- To avoid breaking change, we simply issue warning instead of completely remove the functionality
- The old assignation mode could be disabled by setting GOTEMPLATE_DEPRECATED_ASSIGN=1

For retro-compatibility we add back support for old assignation mode

---

context.go
main_test.go

The bug happened when you called gotemplate like this:
`gotemplate -var test=2.7.4` or `gotemplate -var filename=test.json`. Gotemplate would try to interpret the file and crash. 
What happens now is that the file is interpreted if it exists, otherwise the file name is written as a literal. To have a variable with a literal filename when the file exists (not interpreted) you can call gotemplate like this:
`gotemplate -var filename='exists.json'`

Fix bug where a variable looks like a file but is not

---

template/template_process.go

If there is an error in a non explicit gotemplate file, we used to simply add a notice. But that often resulted in hidding the actual error, so we display it as an error, but still not breaking.

Increase non-breaking error level

---

.vscode/settings.json
Makefile
collections/convert_data.go
collections/convert_data_test.go
collections/implementation/base_helper.go
collections/implementation/generic.go
collections/tests/integrated_data_test.go
hcl/generated_impl.go
hcl/hcl.go
hcl/hcl_test.go
json/generated_impl.go
xml/generated_impl.go
yaml/generated_impl.go

- Rename the function ToNativeRepresentation() to MarshalGo()
- Add error management
- Add support to custom marshaler implementation
- Properly support key tag
- Properly handle empty structure and empty map when omitempty is set
- Add more examples/tests
- Simplify some tests using assert package
- Fix a typo in the Makefile (space missing)

Fix problems when converting objects to go native representation

---

utils/lorem_test.go

Lorem would fail because the RNG wasn't reseeded
```
jduchesne@wks-000685:~/repos/gotemplate$ go test ./... -count=100
ok      github.com/coveooss/gotemplate/v3       8.961s
ok      github.com/coveooss/gotemplate/v3/collections   0.274s
ok      github.com/coveooss/gotemplate/v3/collections/implementation    0.646s
ok      github.com/coveooss/gotemplate/v3/collections/tests     0.112s
ok      github.com/coveooss/gotemplate/v3/errors        0.083s
ok      github.com/coveooss/gotemplate/v3/hcl   0.862s
ok      github.com/coveooss/gotemplate/v3/json  0.776s
ok      github.com/coveooss/gotemplate/v3/template      31.391s
ok      github.com/coveooss/gotemplate/v3/utils 0.154s
ok      github.com/coveooss/gotemplate/v3/xml   0.685s
ok      github.com/coveooss/gotemplate/v3/yaml  0.717s
```

Allow running tests with count > 1

---

docs_tests/advanced_features/pausing_processing.md
docs_tests/advanced_features/pausing_processing.razor
docs_tests/advanced_features/pausing_processing.rendered
template/template.go

To support earlier versions, we want to put a `# gotemplate-pause!` statement that will be handled whenever the gotemplate version is released
`# pause-gotemplate!` is interpreted as explicit gotemplate `# gotemplate!` in earlier version

Change pause statements

---

hcl/hcl_test.go
hcl/utilities.go

The space eating char was not well supported it seems
Unmarshalling a previously marshalled string would give the following error:
"heredoc not terminated"
Also, using EOF is dangerous since it may be used in the actual values

Fix HCL HEREDOC syntax

---

main.go

There was a bug that was introduced by the usage of default command of kingpin.
The command assume that run is the default option. But if we use flags that are specific to the run command, they must be specified after the templates (file or code).
`gotemplate -L2 -R2  '@(2+2)'
was giving an error:
`gotemplate -L2 '@(2+2)' -R2
was working

Fix a bug with argument evaluation

---

docs_tests/basic_features/literals.razor
template/extra_runtime.go
template/razor_expr.go
template/razor_repl_expr.go
template/razor_test.go

The @ should be replaced by a literal @ to ensure that it is not interpreted as a Razor expression.

Fix error when there was an @ in an expression string

---

template/template.go
template/template_handler.go
template/template_test.go

Added functions are no longer wiped when creating a new context

Fix: Functions can now be added to a template without getting a new context

---

template/razor_repl_assign.go
template/razor_test.go

If we write an expression such as:
`@a += 2/3`
we expect to get:
`{{- assertWarning (not (isNil $.a)) "$.a does not exist, use := to declare new variable" }}{{- set $ "a" (add $.a (div 2 3)) }}`
But we got:
`{{ $.a }} = $.a + (div 2 3)`
Which is wrong.
The problem was that the assigned razor expression was converted to go template, then we added the value which resulted in a mixup of razor and go template syntax ...

Fix problem with assignment operators using expression

---

docs_tests/advanced_features/functions.md
docs_tests/advanced_features/functions.razor
docs_tests/advanced_features/functions.rendered
docs_tests/advanced_features/functions/!extensions.gte
template/extra_runtime.go
template/template.go

Global variables set in gotemplate extension (.gte files) should be globally available.

Fix the bug where global variables set in extension where not available

---

collections/convert_data.go
go.sum
hcl/utilities.go
utils/reflect_test.go

It's an HCL behavior, not a native Go data structure behavior

Move list of single map resolution to marshalHCL instead of marshalGo

---

template/extra_data.go
template/template_error_handler.go
template/template_error_handler_test.go
template/template_handler.go
template/template_test.go

No longer switch the error detection to strict mode after discovering one error. That generates error that should not be considered as error otherwise (ex. a if statement with a non existing variable).

Fix the problem where we detect unrelated errors

---

.github/workflows/pr.yml
go.mod
go.sum
template/razor.go

- Update dependencies
There was a rule to escape the dot after an expression. The initial goal was to allow a user writing a expression such as @variable.value but not wanting to expand the variable. So it was possible to write @variable\.value.
But since then, we allowed users to write this kind of expression in various ways.
@variable;.value
@(variable).value
So, letting the \. option available is superfluous and can even lead to error as it become very difficult to render an escaped dot after a gotemplate expression.

Remove Razor dot escaping rule

---

render-doc

Jira DT-4201
I'm not sure when this started to happen but it seems like this was all caused because the `render-doc` script put the description in `<pre>` tags which hugo did not want to render correctly. Switching them to markdown code blocks does the trick.

Fix description not rendering in functions doc

---

template/extra_runtime.go
template/extra_runtime_test.go

Jira: DT-4200
Before this PR, the `exec` function either when invoked directly or when used through the `func` function, would try to template the output of the underlying command. This can lead to some nasty surprises for devs who end up with code that doesn't behave as they expect.

Don't run templating on results of command in exec function

---

.github/dependabot.yml

The changes here are:
- Add the whole team as reviewers
- Reduce the number of open pull requests to 20
- Add updates for github actions
Note to reviewers:
- The indentation changed a bit, hiding whitespaces will help with the review here.
- The removed dependency version has been upgraded past and the ignore is no longer required.

update dependabot config to match other go projects

---

.github/workflows/build.yml

Update peaceiris action to 3.9 via specific hash to comply with CSEC's GHA policy

Csec 18897 migrate peaceiris actions gh pages to hash specific version

---

.github/workflows/build.yml
.github/workflows/pr.yml

Changing the v2.5.0 to it's release hash to comply with CSEC's GHA policy

CSEC-18901 change v2.5.0 to it's release hash

---

.github/workflows/build.yml

Bumping goreleaser-action from 3 to 3.2 via hash to comply with CSEC's GHA policy

CSEC-18899 bumping goreleaser-action from 3 to 3.2

---

utils/terraform.go
utils/terraform_test.go

By file extension, it is incorrect to say that a file with a suffix `.tf.json` is a terraform file, since the extension for such a file is `json`.
https://pkg.go.dev/path/filepath#example-Ext

fix detection of terraform .tf.json file

---

.goreleaser.yml

This fixes the release process. We moved a major version without realizing in #222

Migrate goreleaser config

---

collections/convert_data.go
hcl/hcl.go
main.go
main_test.go
template/extra_git_test.go
template/extra_os.go
template/extra_runtime.go
template/razor_test.go
template/template.go
template/template_error_handler.go
template/template_handler.go
template/template_process.go
template/template_test.go
utilities.go
utils/exec.go

In go v1.16 the `io/ioutil` package is [deprecated](https://go.dev/doc/go1.16#ioutil).

chore: use os and io instead of deprecated io.ioutil

---

.github/workflows/build.yml
.github/workflows/pr.yml

The `actions/setup-go` action can extract the go version from `go.mod`. This will ensure consistency of the go version.

ci: getting go version from go.mod

---

.github/workflows/build.yml
.github/workflows/pr.yml
main.go
render-doc
template/razor.go
template/razor_test.go
template/template.go

This pull request includes several updates to the `gotemplate` project, focusing on upgrading dependencies, adding new features, and improving documentation. The most important changes include updating the Hugo version in the GitHub workflows, adding a new flag for ignoring Razor expressions, and enhancing the `template` package with new functionalities and comprehensive documentation.
* `.github/workflows/build.yml` and `.github/workflows/pr.yml`: Updated Hugo version from `0.82.0` to `0.135.0`. [[1]](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L29-R29) [[2]](diffhunk://#diff-15c806aa509538190832852f439e9921a23bec2da81f95ed0e4bf13c14e5b160L21-R21)
* [`docs/themes/book`](diffhunk://#diff-3280ed9d0882bd20e77c02a4907c5a7d4f5339c9d36fd030ba1484a6e35ca344L1 …

Add a mechanism to ignore some patterns in gotemplate/razor

---

.github/workflows/build.yml

This pull request includes a minor change to the `jobs:` section in the `.github/workflows/build.yml` file. The change updates the arguments passed to the `goreleaser` distribution.
* [`.github/workflows/build.yml`](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L54-R54): Modified the `args` parameter from `release --rm-dist` to `release --clean`.It has been replaced by --clean

Action Go-Releaser deprecated the flag --rm-dist

---

.github/workflows/build.yml

This pull request includes a small change to the `.github/workflows/build.yml` file. The change updates the `uses` statement for the GoReleaser action to use a more readable version reference.
* [`.github/workflows/build.yml`](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L27-R27): Updated `goreleaser/goreleaser-action` to use `@v6` instead of a specific commit hash for better readability and maintainability.Dt 7256

Fix goreleaser-action

---

.github/workflows/build.yml

This pull request includes a small change to the `.github/workflows/build.yml` file. The change updates the version of the `goreleaser` action used in the workflow.
* [`.github/workflows/build.yml`](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L27-R27): Updated the `goreleaser` action to use a specific commit hash `7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8` instead of the version `v6`.

Revert the goreleaser-action to last approved digest

---

template/extra_runtime.go
template/extra_runtime_test.go

| branch | `main` | `feature/dt-7499-optimizeruntemplate` |
|--------|--------|--------|
| **average execution time** | 85,000ms | 1,500ms |
---
- All tests were done using this file with the command `gotemplate -i terraform.tfvars test.gt` :
```
##@ test.gt
@warning(Math.Pi)
@define("func")
@info("called with:", ARGS)
@info("Here's the current branch:", currentBranch("."), "...and pi: ", Math.Pi)
@end 
{{- set $ "region" "us-east-1" }}
{{- $re := reCompile (printf (`(%s-.+) \(.+\)`) "Dev") }}
{{- $all_subnets := dict }}
{{- $describeSubnets := printf "aws ec2 describe-subnets --region %s" $.region }}
{{ warning "FILE_B.gt --- Executing: " $describeSubnets }}
{{ range $subnet := (exec $describeSubnets).Subnets }}
{{ range .Tags }}
@-include("func", "pi?", Math.Pi)
{{ if and (eq .Key …
```

perf: Decrease compute time when using runtime features [DT-7499]
